[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Optional: Add coverage configuration
addopts = --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=term